name: Release

on:
  workflow_dispatch: { }
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Cache local Maven repository
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.m2/repository
          key: blockbind-maven
          restore-keys: |
            blockbind-maven
      - name: Spigot Buildtools 1.16.5
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir buildtools && cd buildtools
          wget "https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar"
          java -jar BuildTools.jar --rev 1.16.5
          cd Bukkit && mvn clean install && cd ..
          cd Spigot && mvn clean install && cd ..
          cd CraftBukkit && mvn clean install && cd ..
          cd ..
      - name: Set up JDK 17
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Spigot Buildtools 1.18
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cd buildtools
          java -jar BuildTools.jar --rev 1.18
          cd Bukkit && mvn clean install && cd ..
          cd Spigot && mvn clean install && cd ..
          cd CraftBukkit && mvn clean install && cd ..
          cd .. && rm -rf buildtools
      - name: Build project
        run: |
          mvn clean package
      - name: Extract Maven project version
        run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        id: project
      - name: Release artifacts
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.project.outputs.version }}"
          prerelease: false
          title: "Block Bind v${{ steps.project.outputs.version }}"
          files: |
            blockbind/bukkit/target/blockbind-bukkit.jar